#!/bin/bash
python client_res_vs_time.py exp1
python client_res_vs_time.py exp2
python client_res_vs_time.py exp3
python client_res_vs_time.py exp4
python client_res_vs_time.py exp5
python client_res_vs_time.py exp6
python client_res_vs_time.py exp7
python client_res_vs_time.py exp8
python client_res_vs_time.py exp9
python client_res_vs_time.py exp10
python client_res_vs_time.py exp11
python client_res_vs_time.py exp12
python client_faces_vs_time.py exp1
python client_faces_vs_time.py exp2
python client_faces_vs_time.py exp3
python client_faces_vs_time.py exp4
python client_faces_vs_time.py exp5
python client_faces_vs_time.py exp6
python client_faces_vs_time.py exp7
python client_faces_vs_time.py exp8
python client_faces_vs_time.py exp9
python client_faces_vs_time.py exp10
python client_faces_vs_time.py exp11
python client_faces_vs_time.py exp12