apiVersion: v1
kind: Service
metadata:
  labels:
    run: echo
  name: echo
  # namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    run: echo
  sessionAffinity: None
  type: NodePort