# kind: Deployment
# apiVersion: extensions/v1beta1
# metadata:
#   name: echo
#   labels:
#     app: echoserver
#     # cheese: wensleydale
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: echoserver
#   template:
#     metadata:
#       labels:
#         app: echoserver
#   spec:
#       containers:
#       - image: stariq/echo
#         imagePullPolicy: Always
#         name: echo
#         ports:
#         - containerPort: 50000
#           protocol: TCP
#         resources:
#           requests:
#             cpu: 100m
#             memory: 50Mi
#           limits:
#             cpu: 100m
#             memory: 50Mi
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       terminationGracePeriodSeconds: 30

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: echo
  name: echo
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: echo
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        run: echo
    spec:
      containers:
      - image: stariq/echo
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 50000
          protocol: TCP
        resources: {}
#         resources:
#           requests:
#             cpu: 100m
#             memory: 50Mi
#           limits:
#             cpu: 100m
#             memory: 50Mi
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
